import {NgModule} from '@angular/core';
import {
    MatButtonModule,
    MatCardModule,
    MatDialogModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatOptionModule,
    MatSelectModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatMenuModule,
    MatStepperModule,
    MatRadioModule
} from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatGridListModule,
        MatListModule,
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatOptionModule,
        MatSelectModule,
        MatTableModule,
        MatSortModule,
        MatDialogModule,
        MatIconModule,
        MatTabsModule,
        MatToolbarModule,
        MatButtonToggleModule,
        MatSidenavModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatStepperModule,
        MatRadioModule
    ],
    exports: [
        MatButtonModule,
        MatGridListModule,
        MatListModule,
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatOptionModule,
        MatSelectModule,
        MatTableModule,
        MatSortModule,
        MatDialogModule,
        MatIconModule,
        MatTabsModule,
        MatToolbarModule,
        MatButtonToggleModule,
        MatSidenavModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatMenuModule,
        MatListModule,
        MatStepperModule,
        MatRadioModule
    ]
})
export class MaterialModule {}
